version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    networks:
      - default
    volumes:
      - ./data/influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_DB=speedtest
  web:
    image: kjake/internet-speedtest-docker:grafana
    container_name: speedweb
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: kjake/internet-speedtest-docker:speedtest
    container_name: speedtest
    networks:
      - default
    environment:
      - TEST_INTERVAL=30

networks:
  default:
    driver: bridge