---
version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    networks:
      - fontend
      - backend
    volumes:
      - ./data/influxdb/:/var/lib/influxdb
    env_file:
      - ./env/db.env
  web:
    image: kjake/internet-speedtest-docker:grafana 
    container_name: speedweb
    ports:
      - "3000:3000"
    networks:
      - fontend
      - backend
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: kjake/internet-speedtest-docker:speedtest
    container_name: speedtest
    networks:
      - backend
    env_file:
      - ./env/testing.env

networks:
  fontend:
    external:
      name: lan
  backend:
    driver: bridge