name: Docker

on:
  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: kjake/internet-speedtest-docker

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_REF##*/}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker image push $IMAGE_NAME:${GITHUB_REF##*/}
